MVCUI/Controllers/DirectorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCUI.Controllers
{
    public class DirectorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCUI/Controllers/GenresController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCUI.Controllers
{
    public class GenresController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCUI/Controllers/MoviesController.cs
using Business.Abstract;
using System.Linq;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using Entities.Dto;

namespace MVCUI.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IDirectorService _directorService;
        private readonly IGenreService _genreService;

        public MoviesController(IMovieService movieService,
                                IDirectorService directorService,
                                IGenreService genreService)
        {
            _movieService = movieService;
            _directorService = directorService;
            _genreService = genreService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = _movieService.GetAll();
            return View(result.Data);
        }

        [HttpPost("/filter")]
        public IActionResult GetByFilter([FromForm] MovieFilterDto filter)
        {
            var result = _movieService.GetByFilter(filter);
            return View(result.Data);
        }

        [HttpGet("/create")]
        public IActionResult CreatePage()
        {
            ViewBag.Genres = GetGenres();
            ViewBag.Directors = GetDirectors();
            return View();
        }

        [HttpGet("/get/{movieId}")]
        public IActionResult GetById(int movieId)
        {
            ViewBag.Genres = GetGenres();
            ViewBag.Directors = GetDirectors();
            var result = _movieService.GetById(movieId);
            return View(result.Data);
        }

        [HttpPost("/add")]
        public IActionResult Add(Movie movie)
        {
            var result=_movieService.Add(movie);
            if(!result.Success) return View(result);
            return RedirectToAction("Index");
        }

        [HttpGet("/delete/{movieId}")]
        public IActionResult Delete(int movieId)
        {
            var result = _movieService.Delete(movieId);
            if (!result.Success) return View(result);
            return RedirectToAction("Index");
        }

        [HttpPost("/update")]
        public IActionResult Update(Movie movie)
        {
            var result = _movieService.Update(movie);
            if (!result.Success) return View(result);
            return RedirectToAction("Index");
        }

        private List<SelectListItem> GetGenres()
        {
            var genres = (from x in _genreService.GetAll().Data
                          select new SelectListItem
                          {
                              Value = x.Id.ToString(),
                              Text = x.Name
                          }).ToList();
            return genres;
        }

        private List<SelectListItem> GetDirectors()
        {
            var directors = (from x in _directorService.GetAll().Data
                             select new SelectListItem
                             {
                                 Value = x.Id.ToString(),
                                 Text = $"{x.FirstName} {x.LastName}"
                             }).ToList();
            return directors;
        }
    }
}

MVCUI/Controllers/SaloonsController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace MVCUI.Controllers
{
    public class SaloonsController : Controller
    {
        private readonly ISaloonService _saloonService;

        public SaloonsController(ISaloonService saloonService)
        {
            _saloonService = saloonService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCUI/ViewComponents/FilterViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace MVCUI.ViewComponents
{
    public class FilterViewComponent : ViewComponent
    {
        private readonly IDirectorService _directorService;
        private readonly IGenreService _genreService;

        public FilterViewComponent(IDirectorService directorService,
                                   IGenreService genreService)
        {
            _directorService = directorService;
            _genreService = genreService;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.Genres = _genreService.GetAll().Data;
            ViewBag.Directors=_directorService.GetAll().Data;
            return View();
        }
    }
}

MVCUI/ViewComponents/MoviesViewComponent.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MVCUI.ViewComponents
{
    public class MoviesViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke(List<Movie> movies)
        {
            return View(movies);
        }
    }
}

MVCUI/Views/Movies/CreatePage.cshtml
@model Movie
@{
    ViewData["Title"] = "CreatePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Add", "Movies", FormMethod.Post))
{
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Film Adı</label>
        @Html.TextBoxFor(x=>x.Name,new {@class="form-control"})
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Tür</label>
        @Html.DropDownListFor(x=>x.GenreId,(List<SelectListItem>) ViewBag.Genres,new {@class="form-control"})
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Yönetmen</label>
        @Html.DropDownListFor(x => x.DirectorId, (List<SelectListItem>) ViewBag.Directors, new { @class = "form-control" })
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Yapım Yılı</label>
        @Html.TextBoxFor(x => x.Year, new { @class = "form-control" ,@type="number"})
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
}

MVCUI/Views/Movies/GetByFilter.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "GetByFilter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync("Movies",Model) 

MVCUI/Views/Movies/GetById.cshtml
@model Movie
@{
    ViewData["Title"] = "GetById";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Update", "Movies", FormMethod.Post))
{
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Film Id</label>
        @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Film Adı</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Tür</label>
        @Html.DropDownListFor(x => x.GenreId, (List<SelectListItem>) ViewBag.Genres, new { @class = "form-control" })
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Yönetmen</label>
        @Html.DropDownListFor(x => x.DirectorId, (List<SelectListItem>) ViewBag.Directors, new { @class = "form-control" })
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Film Adı</label>
        @Html.TextBoxFor(x => x.Year, new { @class = "form-control", @type = "number" })
    </div>
    <button class="btn btn-warning" type="submit">Güncelle</button>
}

MVCUI/Views/Movies/Index.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync("Movies",Model) 

MVCUI/Views/Shared/Components/Filter/Default.cshtml
@{ 
    var genres = ViewBag.Genres as List<Genre>;
    var directors = ViewBag.Directors as List<Director>;
}
<div class="card text-dark bg-light mb-3" style="max-width: 18rem;">
    <div class="card-header">Filtre</div>
    @using (Html.BeginForm("GetByFilter", "Movies", FormMethod.Post))
    {
        <div class="card-body">
            <div class="card">
                <div class="card-header">
                    Tür
                </div>
                <div class="card-body">
                    @for (int i = 0; i < genres.Count; i++)
                    {
                        <div class="d-flex justify-content-between align-content-center">
                            <label class="form-label h6 fw-bold m-0">@genres[i].Name</label>
                            <input type="checkbox" id="@genres[i].Id" name="GenresId[@i]" value="@genres[i].Id" />
                        </div>

                        <hr class="text-dark" />
                    }
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="card">
                <div class="card-header">
                    Yönetmen
                </div>
                <div class="card-body">
                    @for (int i = 0; i < directors.Count; i++)
                    {
                        <div class="d-flex justify-content-between align-content-center">
                            <label class="form-label h6 fw-bold m-0">@($"{directors[i].FirstName} {directors[i].LastName}")</label>
                            <input type="checkbox" id="@directors[i].Id" name="DirectorsId[@i]" value="@directors[i].Id" />
                        </div>

                        <hr class="text-dark" />
                    }
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="card">
                <div class="card-header">
                    Yapım Yılı
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <input class="form-control" type="number" name="MinYear" value="MinYear" placeholder="Min Year" />
                        </div>
                        <div class="col-md-6">
                            <input class="form-control" type="number" name="MaxYear" value="MaxYear" placeholder="Max Year" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-success">Filtrele</button>
        </div>
    }

</div>

MVCUI/Views/Shared/Components/Movies/Default.cshtml
@model List<Movie>

<h1>Filmler</h1>
<hr />
<a class="btn btn-primary mt-2" asp-action="CreatePage">Yeni Film Ekle</a>

<div class="row mt-3">
    <div class="col-md-3">
        @await Component.InvokeAsync("Filter")
    </div>
    <div class="col-md-9">
        <table class="table table-hover table-bordered">

            <thead>
                <tr>
                    <th>Film Id</th>
                    <th>Film Adı</th>
                    <th>Tür</th>
                    <th>Yönetmen</th>
                    <th>Yıl</th>
                    <th>Salonlar</th>
                    <th>Sil</th>
                    <th>Güncelle</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {
                    <tr>
                        <td>@movie.Id</td>
                        <td>@movie.Name</td>
                        <td>@movie.Genre.Name</td>
                        <td>@($"{movie.Director.FirstName} {movie.Director.LastName}")</td>
                        <td>@movie.Year</td>
                        <td>
                            <ul>
                                @foreach (var saloon in movie.MovieSaloons)
                                {
                                    <li>@saloon.Saloon.Name</li>
                                }
                            </ul>
                        </td>
                        <td><a asp-action="Delete" asp-controller="Movies" asp-route-movieId="@movie.Id" class="btn btn-danger">Sil</a></td>
                        <td><a asp-action="GetById" asp-controller="Movies" asp-route-movieId="@movie.Id" class="btn btn-warning">Güncelle</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>